### ISSUE TITLE
Refind is not correctly being registered

### ISSUE THREAD

**Issue by devinburnette** [test-prof/test-prof#307]
**Ruby Version:**
3.2.3

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
RSpec 3.12.0

**TestProf Version:**
1.4.2

### What did you do?
```ruby
# spec/rails_helper.rb

require 'test_prof/recipes/rspec/let_it_be'

TestProf::LetItBe.configure do |config|
  config.default_modifiers[:freeze] = true
  config.report_duplicates = :warn
end
```

```ruby
# simple spec to reproduce the issue

require 'rails_helper'

RSpec.describe 'Refind with LetItBe' do
  let_it_be(:user) { FactoryBot.create(:user) }
  let_it_be(:b4c_user, refind: true) { FactoryBot.create(:b4c_user, investing_user: user) }

  it 'does not raise FrozenError' do
    expect { b4c_user.update!(attribute: 'new_value') }.not_to raise_error
  end
end
```

### What did you expect to happen?
I expected the refind option to get correctly registered and for the FrozenError to get suppressed.

### What actually happened?
The FrozenError is still raised with the hint to add refind, but refind is already added.

```
Failures:

  1) Refind with LetItBe does not raise FrozenError
     Failure/Error: let_it_be(:b4c_user, refind: true) { FactoryBot.create(:b4c_user, investing_user: user) }

     FrozenError:
       can't modify frozen attributes
       If you are using `let_it_be`, you may want to pass `reload: true` or `refind: true` modifier to it.
     # /Users/devinburnette/src/retail/investing/app/models/concerns/active_record_belongs_to.rb:125:in `block (2 levels) in belongs_to'
     # /Users/devinburnette/src/retail/b4c/spec/factories/b4c_users.rb:123:in `block (3 levels) in <main>'
     # ./spec/simple_test_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # FrozenError:
     #   can't modify frozen attributes
     #   /Users/devinburnette/src/retail/investing/app/models/concerns/active_record_belongs_to.rb:125:in `block (2 levels) in belongs_to'
```
